<template>
  <q-page>
    <title-page :breadcrumbs="breadcrumbs"><div class="row items-center justify-between"><div class="text-h6">Configuração documental</div><div class="q-gutter-sm"><q-btn flat color="primary" icon="create_new_folder" label="Nova categoria" dense no-caps @click="categoryDialog=true" /><q-btn color="primary" icon="note_add" label="Novo tipo" dense no-caps @click="typeDialog=true" /></div></div></title-page>
    <div class="q-pa-md">
      <q-banner v-if="loadError" rounded class="bg-red-1 text-negative q-mb-md">{{ loadError }}<template #action><q-btn flat color="negative" label="Tentar novamente" @click="load" /></template></q-banner>
      <div class="row q-col-gutter-md q-mb-md"><div class="col-12 col-md-5"><q-select v-model="categoryFilter" dense outlined clearable emit-value map-options :options="categoryOptions" label="Filtrar por categoria" @update:model-value="loadTypes" /></div><div class="col-12 col-md-7"><q-input v-model="search" dense outlined clearable placeholder="Pesquisar por código ou nome"><template #prepend><q-icon name="search" /></template></q-input></div></div>
      <q-table flat dense hide-pagination row-key="id" :rows="filteredTypes" :columns="columns" :loading="loading" @row-click="(_, row) => openType(row)">
        <template #body-cell-name="props"><q-td :props="props"><q-item dense class="q-pa-none"><q-item-section avatar><q-avatar size="32px" color="blue-grey-1" text-color="blue-grey-7" icon="description" /></q-item-section><q-item-section><q-item-label>{{ props.row.name }}</q-item-label><q-item-label caption>{{ props.row.code }}</q-item-label></q-item-section></q-item></q-td></template>
        <template #body-cell-categoryId="props"><q-td :props="props">{{ categoryName(props.value) }}</q-td></template>
        <template #body-cell-actions="props"><q-td :props="props"><q-btn flat round dense icon="edit" color="primary" aria-label="Configurar tipo documental" @click.stop="openType(props.row)" /></q-td></template>
        <template #no-data><div class="full-width row flex-center q-pa-xl text-grey-7">Nenhum tipo documental encontrado.</div></template>
      </q-table>
    </div>

    <q-dialog v-model="categoryDialog" position="right" full-height><q-card class="side-dialog column no-wrap"><title-card title="Nova categoria" @on-close="categoryDialog=false" /><q-separator /><q-card-section class="scroll col"><q-form ref="categoryForm" @submit.prevent="saveCategory"><form-section title="Identificação"><div class="row q-col-gutter-md"><label-form class-name="col-12 col-sm-4" text-label="Código"><q-input v-model.trim="categoryDraft.code" dense outlined :rules="requiredRules" /></label-form><label-form class-name="col-12 col-sm-8" text-label="Nome"><q-input v-model.trim="categoryDraft.name" dense outlined :rules="requiredRules" /></label-form></div><div class="row justify-end q-mt-lg"><q-btn type="submit" flat color="primary" icon="save" label="Salvar categoria" no-caps :loading="saving" /></div></form-section></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="typeDialog" position="right" full-height><q-card class="side-dialog column no-wrap"><title-card title="Novo tipo documental" @on-close="typeDialog=false" /><q-separator /><q-card-section class="scroll col"><q-form ref="typeForm" @submit.prevent="saveType"><form-section title="Identificação"><div class="row q-col-gutter-md"><label-form class-name="col-12" text-label="Categoria"><q-select v-model="typeDraft.categoryId" dense outlined emit-value map-options :options="categoryOptions" :rules="requiredRules" /></label-form><label-form class-name="col-12 col-sm-4" text-label="Código"><q-input v-model.trim="typeDraft.code" dense outlined :rules="requiredRules" /></label-form><label-form class-name="col-12 col-sm-8" text-label="Nome"><q-input v-model.trim="typeDraft.name" dense outlined :rules="requiredRules" /></label-form><div class="col-12"><q-toggle v-model="typeDraft.requiresExpirationDate" label="Exige data de validade" /></div></div><div class="row justify-end q-mt-lg"><q-btn type="submit" flat color="primary" icon="save" label="Salvar tipo" no-caps :loading="saving" /></div></form-section></q-form></q-card-section></q-card></q-dialog>

    <q-dialog v-model="editorDialog" position="right" full-height><q-card class="editor-dialog column no-wrap"><title-card title="Configurar tipo documental" @on-close="editorDialog=false" /><q-separator /><entity-header v-if="selectedType" :id="selectedType.id" :name="selectedType.name" short-id><template #status><q-badge outline color="primary" class="q-ml-md">{{ selectedType.code }}</q-badge></template></entity-header><q-card-section class="scroll col">
      <form-section title="Países" caption="Associe o país e selecione-o para configurar schemas e definições."><div class="row q-col-gutter-md items-start"><label-form class-name="col-12 col-md-9" text-label="UUID do país"><q-input v-model.trim="countryIdDraft" dense outlined :rules="uuidRules" /></label-form><div class="col-12 col-md-3 q-pt-lg"><q-btn flat dense color="primary" icon="add" label="Associar" no-caps :loading="countrySaving" @click="saveCountry" /></div></div><q-list bordered separator class="q-mt-md"><q-item v-for="country in countries" :key="country.countryId||country.id" clickable :active="countryKey(country)===selectedCountryId" active-class="bg-blue-1 text-primary" @click="selectCountry(country)"><q-item-section><q-item-label>{{ country.name||country.countryName||countryKey(country) }}</q-item-label><q-item-label caption>{{ countryKey(country) }}</q-item-label></q-item-section><q-item-section side><q-badge :color="country.isActive===false?'grey':'positive'">{{ country.isActive===false?'Inativo':'Ativo' }}</q-badge></q-item-section></q-item></q-list></form-section>
      <form-section title="Schemas de metadados" caption="Crie, valide, publique ou retire versões do schema." class="q-mt-lg"><q-banner v-if="!selectedCountryId" rounded class="bg-blue-1 text-primary">Selecione um país para continuar.</q-banner><template v-else><div class="row justify-end q-mb-sm"><q-btn flat dense color="primary" icon="add" label="Novo schema" no-caps @click="schemaDialog=true" /></div><q-table flat dense hide-pagination row-key="id" :rows="schemas" :columns="schemaColumns" :loading="schemaLoading"><template #body-cell-status="props"><q-td :props="props"><q-badge :color="schemaColor(props.value)">{{ props.value }}</q-badge></q-td></template><template #body-cell-actions="props"><q-td :props="props"><row-actions :actions="schemaActions(props.row)" @select="action => runSchemaAction(action, props.row)" /></q-td></template><template #no-data><div class="full-width text-center q-pa-lg text-grey-7">Nenhum schema configurado.</div></template></q-table><div class="row q-gutter-sm q-mt-md"><q-btn flat dense color="primary" icon="cloud_upload" label="Definição de upload" no-caps @click="loadDefinition('upload')" /><q-btn flat dense color="primary" icon="data_object" label="Definição de dados" no-caps @click="loadDefinition('data')" /></div><q-input v-if="definitionText" class="q-mt-md" :model-value="definitionText" type="textarea" autogrow readonly outlined dense label="Definição retornada" /></template></form-section>
    </q-card-section></q-card></q-dialog>

    <q-dialog v-model="schemaDialog"><q-card class="schema-dialog"><title-card title="Novo schema de metadados" @on-close="schemaDialog=false" /><q-separator /><q-card-section><q-form ref="schemaForm" @submit.prevent="saveSchema"><label-form text-label="JSON Schema"><q-input v-model="schemaDraft.schema" type="textarea" rows="10" outlined dense :rules="jsonRules" /></label-form><label-form text-label="UI Schema (opcional)" class="q-mt-md"><q-input v-model="schemaDraft.uiSchema" type="textarea" rows="5" outlined dense :rules="optionalJsonRules" /></label-form><label-form text-label="Resumo da alteração" class="q-mt-md"><q-input v-model.trim="schemaDraft.changeSummary" outlined dense /></label-form><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" icon="save" label="Criar schema" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="instanceDialog"><q-card class="schema-dialog"><title-card title="Validar instância" @on-close="instanceDialog=false" /><q-card-section><q-form @submit.prevent="validateInstance"><label-form text-label="Metadados (JSON)"><q-input v-model="instanceDraft.metadata" type="textarea" rows="8" outlined dense :rules="jsonRules" /></label-form><div class="row q-col-gutter-md q-mt-sm"><label-form class-name="col-6" text-label="Emissão"><q-input v-model="instanceDraft.issuedOn" type="date" outlined dense /></label-form><label-form class-name="col-6" text-label="Validade"><q-input v-model="instanceDraft.expiresOn" type="date" outlined dense /></label-form></div><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" label="Validar" no-caps /></div></q-form></q-card-section></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import TitlePage from 'src/components/TitlePage.vue'; import TitleCard from 'src/components/Card/TitleCard.vue'; import LabelForm from 'src/components/Form/LabelForm.vue'; import FormSection from 'src/components/Entity/FormSection.vue'; import EntityHeader from 'src/components/Entity/EntityHeader.vue'; import RowActions from 'src/components/Entity/RowActions.vue'
import useNotification from 'src/composables/global/useNotification'; import { getApiErrorMessage } from 'src/services/apiError'
import { createDocumentCategory, createDocumentType, createMetadataSchema, getDocumentDataDefinition, getDocumentUploadDefinition, listDocumentCategories, listDocumentTypeCountries, listDocumentTypes, listMetadataSchemas, publishMetadataSchema, retireMetadataSchema, setDocumentTypeCountry, validateMetadataInstance, validateMetadataSchema } from 'src/services/documentAdminService'
const { successNotify,errorNotify }=useNotification(); const breadcrumbs=[{label:'Gestão de Dados'},{label:'Configuração documental'}]
const categories=ref([]),types=ref([]),countries=ref([]),schemas=ref([]),loading=ref(false),schemaLoading=ref(false),saving=ref(false),countrySaving=ref(false),loadError=ref(''),search=ref(''),categoryFilter=ref(null),categoryDialog=ref(false),typeDialog=ref(false),editorDialog=ref(false),schemaDialog=ref(false),instanceDialog=ref(false),selectedType=ref(null),selectedCountryId=ref(null),countryIdDraft=ref(''),definitionText=ref(''),instanceSchema=ref(null),categoryForm=ref(null),typeForm=ref(null),schemaForm=ref(null)
const categoryDraft=reactive({code:'',name:''}),typeDraft=reactive({categoryId:null,code:'',name:'',requiresExpirationDate:false}),schemaDraft=reactive({schema:'{\n  "type": "object",\n  "properties": {}\n}',uiSchema:'',changeSummary:''}),instanceDraft=reactive({metadata:'{}',issuedOn:null,expiresOn:null})
const collection=v=>Array.isArray(v)?v:v?.data||v?.items||[]; const categoryOptions=computed(()=>categories.value.map(c=>({label:`${c.code||''} — ${c.name}`.replace(/^ — /,''),value:c.id}))); const categoryName=id=>categoryOptions.value.find(x=>x.value===id)?.label||id||'—'; const categoryKey=t=>t.categoryId||t.category?.id
const filteredTypes=computed(()=>{const term=search.value.trim().toLowerCase();return types.value.filter(t=>(!categoryFilter.value||categoryKey(t)===categoryFilter.value)&&(!term||`${t.code} ${t.name}`.toLowerCase().includes(term)))}); const columns=[{name:'name',label:'Tipo documental',field:'name',align:'left'},{name:'categoryId',label:'Categoria',field:categoryKey,align:'left'},{name:'requiresExpirationDate',label:'Exige validade',field:'requiresExpirationDate',format:v=>v?'Sim':'Não',align:'left'},{name:'actions',label:'',field:'id',align:'right'}]; const schemaColumns=[{name:'version',label:'Versão',field:'version',align:'left'},{name:'status',label:'Status',field:'status',align:'left'},{name:'changeSummary',label:'Resumo',field:'changeSummary',align:'left'},{name:'actions',label:'',field:'id',align:'right'}]
const requiredRules=[v=>Boolean(String(v||'').trim())||'Campo obrigatório'],uuidRules=[...requiredRules,v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v||'')||'UUID inválido']; const validJson=v=>{try{JSON.parse(v);return true}catch{return 'JSON inválido'}}; const jsonRules=[...requiredRules,validJson],optionalJsonRules=[v=>!v||validJson(v)]
const load=async()=>{loading.value=true;loadError.value='';try{categories.value=collection(await listDocumentCategories());await loadTypes()}catch(e){loadError.value=getApiErrorMessage(e,'Não foi possível carregar a configuração documental.')}finally{loading.value=false}}; const loadTypes=async()=>{types.value=collection(await listDocumentTypes(categoryFilter.value?{categoryId:categoryFilter.value}:{}))}
const saveCategory=async()=>{if(!await categoryForm.value.validate())return;saving.value=true;try{await createDocumentCategory({...categoryDraft});successNotify('Categoria criada.');categoryDialog.value=false;Object.assign(categoryDraft,{code:'',name:''});await load()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível criar a categoria.'))}finally{saving.value=false}}
const saveType=async()=>{if(!await typeForm.value.validate())return;saving.value=true;try{await createDocumentType({...typeDraft});successNotify('Tipo documental criado.');typeDialog.value=false;Object.assign(typeDraft,{categoryId:null,code:'',name:'',requiresExpirationDate:false});await loadTypes()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível criar o tipo documental.'))}finally{saving.value=false}}
const openType=async row=>{selectedType.value=row;selectedCountryId.value=null;countries.value=[];schemas.value=[];definitionText.value='';editorDialog.value=true;try{countries.value=collection(await listDocumentTypeCountries(row.id))}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível carregar os países.'))}}
const countryKey=c=>c.countryId||c.id; const saveCountry=async()=>{if(!uuidRules.every(rule=>rule(countryIdDraft.value)===true))return errorNotify('Informe um UUID de país válido.');countrySaving.value=true;try{await setDocumentTypeCountry(selectedType.value.id,countryIdDraft.value,{isActive:true});successNotify('País associado.');countryIdDraft.value='';countries.value=collection(await listDocumentTypeCountries(selectedType.value.id))}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível associar o país.'))}finally{countrySaving.value=false}}
const selectCountry=async c=>{selectedCountryId.value=countryKey(c);definitionText.value='';await loadSchemas()}; const loadSchemas=async()=>{schemaLoading.value=true;try{schemas.value=collection(await listMetadataSchemas(selectedType.value.id,selectedCountryId.value,{page:1,pageSize:100}))}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível carregar os schemas.'))}finally{schemaLoading.value=false}}
const saveSchema=async()=>{if(!await schemaForm.value.validate())return;saving.value=true;try{await createMetadataSchema(selectedType.value.id,selectedCountryId.value,{schema:schemaDraft.schema,uiSchema:schemaDraft.uiSchema||null,changeSummary:schemaDraft.changeSummary||null});successNotify('Schema criado.');schemaDialog.value=false;await loadSchemas()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível criar o schema.'))}finally{saving.value=false}}
const schemaColor=s=>({Published:'positive',Draft:'grey',Retired:'warning'}[s]||'grey'); const schemaActions=s=>[{name:'validate',label:'Validar schema',icon:'rule'},{name:'instance',label:'Validar instância',icon:'fact_check'},...(s.status==='Published'?[]:[{name:'publish',label:'Publicar',icon:'publish'}]),...(s.status==='Retired'?[]:[{name:'retire',label:'Retirar',icon:'archive'}])]
const runSchemaAction=async(action,s)=>{if(action==='instance'){instanceSchema.value=s;instanceDialog.value=true;return}try{if(action==='validate')await validateMetadataSchema(selectedType.value.id,selectedCountryId.value,s.id);if(action==='publish')await publishMetadataSchema(selectedType.value.id,selectedCountryId.value,s.id);if(action==='retire')await retireMetadataSchema(selectedType.value.id,selectedCountryId.value,s.id);successNotify('Ação concluída.');await loadSchemas()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível concluir a ação.'))}}
const validateInstance=async()=>{try{await validateMetadataInstance(selectedType.value.id,selectedCountryId.value,instanceSchema.value.id,{...instanceDraft,issuedOn:instanceDraft.issuedOn||null,expiresOn:instanceDraft.expiresOn||null});successNotify('Instância válida.');instanceDialog.value=false}catch(e){errorNotify(getApiErrorMessage(e,'A instância não é válida.'))}}
const loadDefinition=async kind=>{try{const d=kind==='upload'?await getDocumentUploadDefinition(selectedType.value.id,selectedCountryId.value):await getDocumentDataDefinition(selectedType.value.id,selectedCountryId.value);definitionText.value=JSON.stringify(d,null,2)}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível carregar a definição.'))}}
onMounted(load)
</script>
<style scoped>.side-dialog{width:min(620px,100vw)}.editor-dialog{width:min(900px,100vw)}.schema-dialog{width:min(720px,calc(100vw - 32px))}</style>
