import { api } from 'src/boot/axios'

const unwrap = (response) => response.data?.data ?? response.data
const base = '/api/v1/admin/document-types'

export const listDocumentCategories = async () => unwrap(await api.get('/api/v1/admin/document-categories'))
export const createDocumentCategory = async (payload) => unwrap(await api.post('/api/v1/admin/document-categories', payload))
export const listDocumentTypes = async (params = {}) => unwrap(await api.get(base, { params }))
export const createDocumentType = async (payload) => unwrap(await api.post(base, payload))
export const listDocumentTypeCountries = async (typeId) => unwrap(await api.get(`${base}/${typeId}/countries`))
export const setDocumentTypeCountry = async (typeId, countryId, payload) => unwrap(await api.put(`${base}/${typeId}/countries/${countryId}`, payload))
export const deactivateDocumentTypeCountry = async (typeId, countryId) => unwrap(await api.delete(`${base}/${typeId}/countries/${countryId}`))
export const listMetadataSchemas = async (typeId, countryId, params = {}) => unwrap(await api.get(`${base}/${typeId}/countries/${countryId}/metadata-schemas`, { params }))
export const createMetadataSchema = async (typeId, countryId, payload) => unwrap(await api.post(`${base}/${typeId}/countries/${countryId}/metadata-schemas`, payload))
export const validateMetadataSchema = async (typeId, countryId, schemaId) => unwrap(await api.post(`${base}/${typeId}/countries/${countryId}/metadata-schemas/${schemaId}/validate`))
export const validateMetadataInstance = async (typeId, countryId, schemaId, payload) => unwrap(await api.post(`${base}/${typeId}/countries/${countryId}/metadata-schemas/${schemaId}/validate-instance`, payload))
export const publishMetadataSchema = async (typeId, countryId, schemaId) => unwrap(await api.post(`${base}/${typeId}/countries/${countryId}/metadata-schemas/${schemaId}/publish`))
export const retireMetadataSchema = async (typeId, countryId, schemaId) => unwrap(await api.post(`${base}/${typeId}/countries/${countryId}/metadata-schemas/${schemaId}/retire`))
export const getDocumentUploadDefinition = async (typeId, countryId) => unwrap(await api.get(`${base}/${typeId}/countries/${countryId}/upload-definition`))
export const getDocumentDataDefinition = async (typeId, countryId) => unwrap(await api.get(`${base}/${typeId}/countries/${countryId}/data-definition`))
export const listCustomerDocumentRequirements = async (customerId) => unwrap(await api.get(`/api/v1/admin/customers/${customerId}/document-requirements`))
export const createCustomerDocumentRequirement = async (customerId, payload) => unwrap(await api.post(`/api/v1/admin/customers/${customerId}/document-requirements`, payload))
export const listCustomerDocuments = async (customerId, params = {}) => unwrap(await api.get(`/api/v1/admin/customers/${customerId}/documents`, { params }))
export const getCustomerDocumentOverview = async (customerId) => unwrap(await api.get(`/api/v1/admin/customers/${customerId}/documents/overview`))
export const getCustomerDocumentProgress = async (customerId) => unwrap(await api.get(`/api/v1/admin/customers/${customerId}/documents/progress`))
export const uploadCustomerDocument = async (customerId, data) => unwrap(await api.post(`/api/v1/admin/customers/${customerId}/documents`, data))
export const reviewDocument = async (id, payload) => unwrap(await api.post(`/api/v1/admin/documents/${id}/reviews`, payload))
export const changeDocumentStatus = async (id, status) => unwrap(await api.patch(`/api/v1/admin/documents/${id}/status`, { status }))
export const deleteDocument = async (id) => unwrap(await api.delete(`/api/v1/admin/documents/${id}`))
export const downloadDocument = async (id) => api.get(`/api/v1/admin/documents/${id}/download`, { responseType: 'blob' })
export const getDocumentTemporaryUrl = async (id, expiresInMinutes = 15) => unwrap(await api.get(`/api/v1/admin/documents/${id}/temporary-url`, { params: { expiresInMinutes } }))
