<template>
  <div>
    <div class="row items-center justify-between"><div><div class="text-subtitle1 text-weight-bold">Compliance</div><div class="text-caption text-grey-7">Flags, alertas e histórico interno do cliente.</div></div><q-btn flat dense size="sm" color="primary" icon="add_alert" label="Nova flag" no-caps @click="openCreate" /></div>
    <q-banner v-if="error" class="bg-red-1 text-negative q-mt-md">{{ error }}<template #action><q-btn flat color="negative" label="Tentar novamente" @click="load" /></template></q-banner><div v-if="loading" class="row justify-center q-pa-xl"><q-spinner color="primary" size="32px" /></div>
    <template v-else>
      <div class="panel-metrics q-mt-md">
        <div class="panel-metric panel-metric--wide"><span>Situação</span><strong :class="cardClass">{{ card.status || card.riskLevel || 'Sem flags pendentes' }}</strong></div>
        <div class="panel-metric"><span>Flags abertas</span><strong>{{ card.openFlagsCount ?? openFlags.length }}</strong></div>
        <div class="panel-metric"><span>Alertas</span><strong>{{ alerts.length }}</strong></div>
      </div>
      <section class="panel-section">
        <h3>Flags</h3>
        <q-table class="panel-table" flat dense hide-pagination row-key="id" :rows="flags" :columns="columns"><template #body-cell-severity="p"><q-td :props="p"><q-badge :color="severityColor(p.value)">{{ p.value }}</q-badge></q-td></template><template #body-cell-status="p"><q-td :props="p"><q-badge outline color="primary">{{ p.value }}</q-badge></q-td></template><template #body-cell-actions="p"><q-td :props="p"><row-actions :actions="actions(p.row)" @select="a=>runAction(a,p.row)" /></q-td></template><template #no-data><div class="panel-empty full-width text-center">Nenhuma flag cadastrada.</div></template></q-table>
      </section>
      <section class="panel-section">
        <h3>Alertas</h3>
        <q-list v-if="alerts.length" separator class="panel-list"><q-item v-for="a in alerts" :key="a.id||a.code"><q-item-section><q-item-label>{{ a.title||a.message||a.type }}</q-item-label><q-item-label caption>{{ a.description }}</q-item-label></q-item-section></q-item></q-list><div v-else class="panel-empty">Nenhum alerta ativo.</div>
      </section>
      <section class="panel-section">
        <h3>Histórico</h3>
        <q-list v-if="history.length" separator class="panel-list"><q-item v-for="h in history" :key="h.id"><q-item-section><q-item-label>{{ h.title||h.action||h.eventType }}</q-item-label><q-item-label caption>{{ h.description||h.notes }} · {{ formatDate(h.createdAtUtc||h.occurredAtUtc) }}</q-item-label></q-item-section></q-item></q-list><div v-else class="panel-empty">Nenhum evento registrado.</div>
      </section>
    </template>
    <q-dialog v-model="formDialog"><q-card dark class="form-dialog"><title-card :title="editingId?'Editar flag':'Nova flag de compliance'" @on-close="formDialog=false" /><q-card-section><q-form ref="formRef" @submit.prevent="save"><div class="row q-col-gutter-md"><label-form class-name="col-12 col-md-6" text-label="Tipo"><q-select v-model="draft.flagType" dark outlined dense emit-value map-options options-dense :options="flagTypes" :disable="Boolean(editingId)" :rules="requiredRules" /></label-form><label-form class-name="col-12 col-md-6" text-label="Severidade"><q-select v-model="draft.severity" dark outlined dense emit-value map-options :options="severities" :rules="requiredRules" /></label-form><label-form v-if="!editingId" class-name="col-12" text-label="Título"><q-input v-model.trim="draft.title" dark outlined dense :rules="requiredRules" /></label-form><label-form class-name="col-12" text-label="Descrição"><q-input v-model.trim="draft.description" dark type="textarea" outlined dense /></label-form><label-form class-name="col-12 col-md-6" text-label="Status"><q-select v-model="draft.status" dark outlined dense emit-value map-options :options="statuses" /></label-form><label-form class-name="col-12 col-md-6" text-label="Frequência de monitoramento"><q-input v-model.trim="draft.monitoringFrequency" dark outlined dense /></label-form><label-form v-if="!editingId" class-name="col-12 col-md-6" text-label="Detectado por"><q-select v-model="draft.detectedBy" dark outlined dense emit-value map-options options-dense :options="detectedByOptions" :rules="requiredRules" /></label-form><label-form v-if="!editingId" class-name="col-12 col-md-6" text-label="Detectado em"><q-input v-model="draft.detectedAtUtc" dark type="datetime-local" outlined dense /></label-form><label-form class-name="col-12 col-md-6" text-label="Relação PEP"><q-input v-model.trim="draft.relatedPepRelationship" dark outlined dense /></label-form><label-form class-name="col-12 col-md-6" text-label="Descrição PEP"><q-input v-model.trim="draft.relatedPepDescription" dark outlined dense /></label-form><label-form v-if="!editingId" class-name="col-12" text-label="Evidência (JSON opcional)"><q-input v-model.trim="draft.evidence" dark type="textarea" outlined dense :rules="evidenceRules" /></label-form></div><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" icon="save" label="Salvar flag" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="decisionDialog"><q-card dark class="form-dialog"><title-card :title="decision==='resolve'?'Resolver flag':'Descartar flag'" @on-close="decisionDialog=false" /><q-card-section><q-form @submit.prevent="saveDecision"><label-form text-label="Justificativa"><q-input v-model.trim="decisionDescription" dark type="textarea" outlined :rules="requiredRules" /></label-form><div class="row justify-end q-mt-md"><q-btn type="submit" flat :color="decision==='resolve'?'positive':'negative'" label="Confirmar" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
  </div>
</template>
<script setup>
import{computed,reactive,ref,watch}from'vue';import TitleCard from'src/components/Card/TitleCard.vue';import LabelForm from'src/components/Form/LabelForm.vue';import RowActions from'src/components/Entity/RowActions.vue';import useNotification from'src/composables/global/useNotification';import{getApiErrorMessage}from'src/services/apiError';import{createComplianceFlag,dismissComplianceFlag,getComplianceAlerts,getComplianceCard,getComplianceHistory,listComplianceFlags,resolveComplianceFlag,updateComplianceFlag}from'src/services/complianceService'
const props=defineProps({customerId:{type:String,required:true}}),emit=defineEmits(['updated']),{successNotify,errorNotify}=useNotification(),loading=ref(true),saving=ref(false),error=ref(''),card=ref({}),flags=ref([]),alerts=ref([]),history=ref([]),formDialog=ref(false),decisionDialog=ref(false),formRef=ref(null),editingId=ref(null),target=ref(null),decision=ref('resolve'),decisionDescription=ref('');const empty=()=>({flagType:'ManualObservation',severity:'Medium',status:'Active',title:'',description:'',monitoringFrequency:'',detectedBy:'User',detectedAtUtc:'',relatedPepDescription:'',relatedPepRelationship:'',evidence:''}),draft=reactive(empty()),collection=v=>Array.isArray(v)?v:v?.data||v?.items||[]
const columns=[{name:'title',label:'Flag',field:r=>r.title||r.flagType,align:'left'},{name:'severity',label:'Severidade',field:'severity',align:'left'},{name:'status',label:'Status',field:'status',align:'left'},{name:'actions',label:'',field:'id',align:'right'}],flagTypes=[{label:'Pessoa politicamente exposta (PEP)',value:'Pep'},{label:'Relacionado a PEP',value:'RelatedPep'},{label:'Sanções',value:'Sanctions'},{label:'Mídia adversa',value:'AdverseMedia'},{label:'País de alto risco',value:'HighRiskCountry'},{label:'Observação manual',value:'ManualObservation'}],severities=['Low','Medium','High','Critical'].map(v=>({label:v,value:v})),statuses=[{label:'Ativa',value:'Active'},{label:'Em análise',value:'UnderReview'},{label:'Resolvida',value:'Resolved'},{label:'Descartada',value:'Dismissed'}],detectedByOptions=[{label:'Usuário',value:'User'},{label:'Sistema',value:'System'},{label:'Provedor',value:'Provider'},{label:'Integração',value:'Integration'}],requiredRules=[v=>Boolean(String(v||'').trim())||'Campo obrigatório'],evidenceRules=[v=>{if(!v)return true;try{const parsed=JSON.parse(v);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)||'Informe um objeto JSON válido'}catch{return'Informe um objeto JSON válido'}}],openFlags=computed(()=>flags.value.filter(f=>!['Resolved','Dismissed'].includes(f.status))),cardClass=computed(()=>openFlags.value.length?'text-negative':'text-positive')
const load=async()=>{loading.value=true;error.value='';const names=['card','flags','alertas','histórico'];const results=await Promise.allSettled([getComplianceCard(props.customerId),listComplianceFlags(props.customerId,{page:1,pageSize:100}),getComplianceAlerts(props.customerId),getComplianceHistory(props.customerId,{page:1,pageSize:100})]);if(results[0].status==='fulfilled')card.value=results[0].value||{};if(results[1].status==='fulfilled')flags.value=collection(results[1].value);if(results[2].status==='fulfilled')alerts.value=collection(results[2].value);if(results[3].status==='fulfilled')history.value=collection(results[3].value);const failed=results.map((r,i)=>r.status==='rejected'?names[i]:null).filter(Boolean);if(failed.length)error.value=`Não foi possível carregar: ${failed.join(', ')}.`;loading.value=false},actions=f=>[{name:'edit',label:'Editar',icon:'edit'},...(!['Resolved','Dismissed'].includes(f.status)?[{name:'resolve',label:'Resolver',icon:'check_circle',color:'positive'},{name:'dismiss',label:'Descartar',icon:'cancel',color:'negative'}]:[])],openCreate=()=>{editingId.value=null;Object.assign(draft,empty());formDialog.value=true}
const normalizeStatus=s=>({Open:'Active',Monitoring:'UnderReview'}[s]||s),runAction=(a,f)=>{target.value=f;if(a==='edit'){editingId.value=f.id;Object.assign(draft,{...empty(),...f,status:normalizeStatus(f.status),evidence:''});formDialog.value=true;return}decision.value=a;decisionDescription.value='';decisionDialog.value=true},save=async()=>{if(!await formRef.value.validate())return;saving.value=true;try{if(editingId.value)await updateComplianceFlag(props.customerId,editingId.value,{severity:draft.severity,status:draft.status,description:draft.description||null,monitoringFrequency:draft.monitoringFrequency||null,relatedPepDescription:draft.relatedPepDescription||null,relatedPepRelationship:draft.relatedPepRelationship||null});else await createComplianceFlag(props.customerId,{...draft,detectedAtUtc:draft.detectedAtUtc?new Date(draft.detectedAtUtc).toISOString():null,description:draft.description||null,monitoringFrequency:draft.monitoringFrequency||null,relatedPepDescription:draft.relatedPepDescription||null,relatedPepRelationship:draft.relatedPepRelationship||null,evidence:draft.evidence?JSON.parse(draft.evidence):null});successNotify('Flag salva.');formDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível salvar a flag.'))}finally{saving.value=false}},saveDecision=async()=>{saving.value=true;try{const fn=decision.value==='resolve'?resolveComplianceFlag:dismissComplianceFlag;await fn(props.customerId,target.value.id,decisionDescription.value||null);successNotify(decision.value==='resolve'?'Flag resolvida.':'Flag descartada.');decisionDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível concluir a ação.'))}finally{saving.value=false}},refresh=async()=>{await load();emit('updated')},severityColor=s=>({Low:'grey',Medium:'warning',High:'orange',Critical:'negative'}[s]||'grey'),formatDate=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';watch(()=>props.customerId,load,{immediate:true})
</script><style scoped>
.form-dialog { width: min(720px, calc(100vw - 32px)); color: #fff; border: 1px solid rgba(255,255,255,.14); border-radius: 14px; background: linear-gradient(145deg, rgba(8,12,24,.98), rgba(5,24,42,.98)); box-shadow: 0 24px 70px rgba(0,0,0,.48); backdrop-filter: blur(20px); }
.form-dialog :deep(.q-field__native), .form-dialog :deep(.q-field__input), .form-dialog :deep(.q-field__label) { color: #fff; }
.form-dialog :deep(.q-field--outlined .q-field__control::before) { border-color: rgba(255,255,255,.28); }
.panel-metrics { display: grid; grid-template-columns: minmax(220px, 1.5fr) repeat(2, minmax(130px, .5fr)); gap: 12px; }
.panel-metric { min-height: 86px; padding: 16px; border: 1px solid rgba(127,127,127,.22); border-radius: 8px; background: rgba(127,127,127,.045); }
.panel-metric span { display: block; font-size: 12px; opacity: .62; }
.panel-metric strong { display: block; margin-top: 8px; font-size: 18px; font-weight: 600; }
.panel-metric--wide strong { font-size: 14px; }
.panel-section { margin-top: 24px; }
.panel-section h3 { margin: 0 0 10px; font-size: 14px; font-weight: 600; }
.panel-list, .panel-table { overflow: hidden; color: inherit; border: 1px solid rgba(127,127,127,.22); border-radius: 8px; background: rgba(127,127,127,.035); }
.panel-list :deep(.q-item__label--caption), .panel-list :deep(.q-item__section--side) { color: inherit; opacity: .62; }
.panel-table :deep(.q-table), .panel-table :deep(th), .panel-table :deep(td) { color: inherit; background: transparent; }
.panel-table :deep(th) { font-size: 12px; opacity: .68; }
.panel-table :deep(td), .panel-table :deep(th) { border-color: rgba(127,127,127,.18); }
.panel-empty { padding: 24px 16px; border: 1px dashed rgba(127,127,127,.28); border-radius: 8px; font-size: 12px; opacity: .62; }
@media (max-width: 700px) { .panel-metrics { grid-template-columns: 1fr; } }
</style>
