<template>
  <div class="client-documents-panel">
    <div class="row items-center justify-between"><div><div class="text-subtitle1 text-weight-bold">Documentos</div><div class="text-caption text-grey-7">Requisitos, progresso e revisão documental do cliente.</div></div><div class="q-gutter-xs"><q-btn flat dense size="sm" color="primary" icon="rule" label="Novo requisito" no-caps @click="requirementDialog=true" /><q-btn flat dense size="sm" color="primary" icon="upload_file" label="Enviar" no-caps @click="uploadDialog=true" /></div></div>
    <q-banner v-if="error" class="bg-red-1 text-negative q-mt-md">{{ error }}<template #action><q-btn flat color="negative" label="Tentar novamente" @click="load" /></template></q-banner>
    <div v-if="loading" class="row justify-center q-pa-xl"><q-spinner color="primary" size="32px" /></div>
    <template v-else-if="!error">
      <div class="row q-col-gutter-md q-mt-sm"><div class="col-12 col-md-6"><q-banner rounded class="bg-blue-1 text-primary"><div class="text-caption">Documentos cadastrados</div><div class="text-h6">{{ totalDocuments }}</div></q-banner></div><div class="col-12 col-md-6"><q-banner rounded class="bg-blue-1 text-primary"><div class="text-caption">Progresso documental</div><q-linear-progress class="q-my-xs" rounded :value="progressPercentage/100" /><div>{{ progressPercentage }}%</div></q-banner></div></div>
      <div class="text-weight-medium q-mt-lg q-mb-sm">Requisitos</div><q-list v-if="requirements.length" bordered separator><q-item v-for="item in requirements" :key="item.id"><q-item-section><q-item-label>{{ typeName(item.documentTypeId) }}</q-item-label><q-item-label caption>Prazo: {{ formatDate(item.dueDate) }}</q-item-label></q-item-section><q-item-section side><q-badge :color="item.isSatisfied?'positive':'warning'">{{ item.isSatisfied?'Atendido':'Pendente' }}</q-badge></q-item-section></q-item></q-list><div v-else class="text-caption text-grey-7">Nenhum requisito cadastrado.</div>
      <div class="text-weight-medium q-mt-lg q-mb-sm">Arquivos</div><q-table flat dense hide-pagination row-key="id" :rows="documents" :columns="columns"><template #body-cell-name="props"><q-td :props="props">{{ props.row.documentTypeName||typeName(props.row.documentTypeId) }}</q-td></template><template #body-cell-status="props"><q-td :props="props"><q-badge :color="statusColor(props.value)">{{ statusLabel(props.value) }}</q-badge></q-td></template><template #body-cell-actions="props"><q-td :props="props"><row-actions :actions="documentActions" @select="action=>runAction(action,props.row)" /></q-td></template><template #no-data><div class="full-width text-center text-grey-7 q-pa-lg">Nenhum documento enviado.</div></template></q-table>
    </template>

    <q-dialog v-model="requirementDialog"><q-card class="form-dialog"><title-card title="Novo requisito documental" @on-close="requirementDialog=false" /><q-card-section><q-form ref="requirementForm" @submit.prevent="saveRequirement"><label-form text-label="Tipo documental"><q-select v-model="requirementDraft.documentTypeId" dense outlined emit-value map-options :options="typeOptions" :rules="requiredRules" /></label-form><label-form text-label="Prazo" class="q-mt-md"><q-input v-model="requirementDraft.dueDate" type="date" dense outlined /></label-form><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" icon="save" label="Criar requisito" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="uploadDialog"><q-card class="form-dialog"><title-card title="Enviar documento" @on-close="uploadDialog=false" /><q-card-section><q-form ref="uploadForm" @submit.prevent="saveUpload"><label-form text-label="Tipo documental"><q-select v-model="uploadDraft.documentTypeId" dense outlined emit-value map-options :options="typeOptions" :rules="requiredRules" /></label-form><label-form text-label="Requisito (opcional)" class="q-mt-md"><q-select v-model="uploadDraft.requirementId" dense outlined clearable emit-value map-options :options="requirementOptions" /></label-form><label-form text-label="País (UUID, opcional)" class="q-mt-md"><q-input v-model.trim="uploadDraft.countryId" dense outlined /></label-form><label-form text-label="Arquivo" class="q-mt-md"><q-file v-model="uploadDraft.file" dense outlined accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" max-file-size="26214400" :rules="fileRules" @rejected="fileRejected" /></label-form><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" icon="upload" label="Enviar" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="reviewDialog"><q-card class="form-dialog"><title-card title="Revisar documento" @on-close="reviewDialog=false" /><q-card-section><q-form @submit.prevent="saveReview"><label-form text-label="Decisão"><q-select v-model="reviewDraft.status" dense outlined emit-value map-options :options="reviewStatuses" :rules="requiredRules" /></label-form><label-form text-label="Motivo/observação" class="q-mt-md"><q-input v-model.trim="reviewDraft.notes" type="textarea" outlined :rules="reviewDraft.status==='Rejected'?requiredRules:[]" /></label-form><div class="row justify-end q-mt-md"><q-btn type="submit" flat color="primary" label="Concluir revisão" no-caps :loading="saving" /></div></q-form></q-card-section></q-card></q-dialog>
    <q-dialog v-model="deleteDialog"><q-card class="form-dialog"><q-card-section><div class="text-subtitle1 text-weight-bold">Excluir documento?</div><div class="q-mt-sm">Use apenas para arquivos descartáveis de homologação.</div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup /><q-btn flat color="negative" label="Excluir" :loading="saving" @click="confirmDelete" /></q-card-actions></q-card></q-dialog>
  </div>
</template>
<script setup>
import { computed, reactive, ref, watch } from 'vue'; import TitleCard from 'src/components/Card/TitleCard.vue'; import LabelForm from 'src/components/Form/LabelForm.vue'; import RowActions from 'src/components/Entity/RowActions.vue'; import useNotification from 'src/composables/global/useNotification'; import { getApiErrorMessage } from 'src/services/apiError'
import { changeDocumentStatus, createCustomerDocumentRequirement, deleteDocument, downloadDocument, getCustomerDocumentOverview, getCustomerDocumentProgress, getDocumentTemporaryUrl, listCustomerDocumentRequirements, listCustomerDocuments, listDocumentTypes, reviewDocument, uploadCustomerDocument } from 'src/services/documentAdminService'
const props=defineProps({customerId:{type:String,required:true}}),emit=defineEmits(['updated']);const{successNotify,errorNotify}=useNotification();const loading=ref(true),saving=ref(false),error=ref(''),requirements=ref([]),documents=ref([]),types=ref([]),overview=ref({}),progress=ref({}),requirementDialog=ref(false),uploadDialog=ref(false),reviewDialog=ref(false),deleteDialog=ref(false),requirementForm=ref(null),uploadForm=ref(null),target=ref(null)
const requirementDraft=reactive({documentTypeId:null,dueDate:null}),uploadDraft=reactive({documentTypeId:null,requirementId:null,countryId:'',file:null}),reviewDraft=reactive({status:'Approved',notes:''});const collection=v=>Array.isArray(v)?v:v?.data||v?.items||[];const typeOptions=computed(()=>types.value.map(t=>({label:t.name||t.code,value:t.id}))),requirementOptions=computed(()=>requirements.value.map(r=>({label:typeName(r.documentTypeId),value:r.id})));const typeName=id=>typeOptions.value.find(t=>t.value===id)?.label||'Documento';const totalDocuments=computed(()=>overview.value.totalDocuments??overview.value.total??documents.value.length),progressPercentage=computed(()=>Math.max(0,Math.min(100,Number(progress.value.percentage??progress.value.progressPercentage??progress.value.progress??0))))
const columns=[{name:'name',label:'Documento',field:'documentTypeName',align:'left'},{name:'fileName',label:'Arquivo',field:r=>r.fileName||r.originalFileName||'Protegido',align:'left'},{name:'status',label:'Status',field:'status',align:'left'},{name:'actions',label:'',field:'id',align:'right'}],documentActions=[{name:'download',label:'Baixar',icon:'download'},{name:'url',label:'Link temporário',icon:'link'},{name:'review',label:'Revisar',icon:'rate_review'},{name:'status',label:'Marcar em análise',icon:'pending_actions'},{name:'delete',label:'Excluir',icon:'delete',color:'negative'}],reviewStatuses=[{label:'Aprovar',value:'Approved'},{label:'Rejeitar',value:'Rejected'}],requiredRules=[v=>Boolean(v)||'Campo obrigatório'],fileRules=[v=>Boolean(v)||'Selecione um arquivo',v=>!v||['application/pdf','image/jpeg','image/png'].includes(v.type)||'Use PDF, JPEG ou PNG',v=>!v||v.size<=26214400||'Máximo de 25 MB']
const statusLabel=s=>({Approved:'Aprovado',Rejected:'Rejeitado',UnderReview:'Em análise',Pending:'Pendente'}[s]||s||'Enviado'),statusColor=s=>({Approved:'positive',Rejected:'negative',UnderReview:'warning',Pending:'grey'}[s]||'grey'),formatDate=v=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(`${v}T00:00:00`)):'Sem prazo'
const load=async()=>{loading.value=true;error.value='';try{const[r,d,t,o,p]=await Promise.all([listCustomerDocumentRequirements(props.customerId),listCustomerDocuments(props.customerId,{page:1,pageSize:100}),listDocumentTypes(),getCustomerDocumentOverview(props.customerId),getCustomerDocumentProgress(props.customerId)]);requirements.value=collection(r);documents.value=collection(d);types.value=collection(t);overview.value=o||{};progress.value=p||{}}catch(e){error.value=getApiErrorMessage(e,'Não foi possível carregar os documentos.')}finally{loading.value=false}}
const saveRequirement=async()=>{if(!await requirementForm.value.validate())return;saving.value=true;try{await createCustomerDocumentRequirement(props.customerId,{documentTypeId:requirementDraft.documentTypeId,dueDate:requirementDraft.dueDate||null});successNotify('Requisito criado.');requirementDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível criar o requisito.'))}finally{saving.value=false}},fileRejected=()=>errorNotify('Use PDF, JPEG ou PNG com até 25 MB.')
const saveUpload=async()=>{if(!await uploadForm.value.validate())return;saving.value=true;try{const data=new FormData();data.append('file',uploadDraft.file);data.append('documentTypeId',uploadDraft.documentTypeId);if(uploadDraft.requirementId)data.append('requirementId',uploadDraft.requirementId);if(uploadDraft.countryId)data.append('countryId',uploadDraft.countryId);await uploadCustomerDocument(props.customerId,data);successNotify('Documento enviado.');uploadDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível enviar o documento.'))}finally{saving.value=false}}
const runAction=async(a,d)=>{target.value=d;if(a==='review'){Object.assign(reviewDraft,{status:'Approved',notes:''});reviewDialog.value=true;return}if(a==='delete'){deleteDialog.value=true;return}try{if(a==='download'){const r=await downloadDocument(d.id),u=URL.createObjectURL(r.data),link=document.createElement('a');link.href=u;link.download=d.fileName||'documento';link.click();URL.revokeObjectURL(u)}if(a==='url'){const r=await getDocumentTemporaryUrl(d.id),u=r.url||r.temporaryUrl;if(!u)throw new Error('URL ausente');window.open(u,'_blank','noopener')}if(a==='status')await changeDocumentStatus(d.id,'UnderReview');if(a==='status')await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível concluir a ação.'))}}
const saveReview=async()=>{saving.value=true;try{await reviewDocument(target.value.id,{...reviewDraft,notes:reviewDraft.notes||null});successNotify('Revisão concluída.');reviewDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível revisar o documento.'))}finally{saving.value=false}},confirmDelete=async()=>{saving.value=true;try{await deleteDocument(target.value.id);successNotify('Documento excluído.');deleteDialog.value=false;await refresh()}catch(e){errorNotify(getApiErrorMessage(e,'Não foi possível excluir o documento.'))}finally{saving.value=false}},refresh=async()=>{await load();emit('updated')};watch(()=>props.customerId,load,{immediate:true})
</script><style scoped>.form-dialog{width:min(620px,calc(100vw - 32px))}</style>
